apiVersion: v1
kind: Service
metadata:
  name: rundeck-app
  labels:
    app: rundeck
spec:
  ports:
    - name: webui
      port: 4440
      protocol: TCP
  selector:
    app: rundeck
  type: NodePort
