apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: rundeck
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: rundeck
    spec:
      volumes:
           - name: rundeck-projects
             emptyDir: {}
           - name: rundeck-data
             emptyDir: {}
      containers:
        - name: rundeck
          image: rundeck/rundeck:3.0.12
          env:
            - name: RUNDECK_GRAILS_URL
              value: http://172.21.20.53:31386
          ports:
            - name: http-port
              containerPort: 4440
          volumeMounts:
            - name: rundeck-projects
              mountPath: /home/rundeck/projects
            - name: rundeck-data
              mountPath: /home/rundeck/server/data
