apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: grafana
  name: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      run: grafana
  template:
    metadata:
      labels:
        run: grafana
        version: 2.1.0
    spec:
      securityContext:
        fsGroup: 472
      containers:
      - image: gcr.io/alliar-211216/grafana@sha256:1ad5492250a898afba91c7dcacddb763cdb40e1d1c74cde2f7a6260b4f5365c3
        name: grafana
        ports:
        - containerPort: 3000
        volumeMounts:
        - name: "grafana-data"
          mountPath: "/var/lib/grafana"
        - name: "certalliar"
          mountPath: "/etc/grafana/tls/"
        - name: "grafana-ini"
          mountPath: "/etc/grafana/"
        securityContext:
          allowPrivilegeEscalation: false
      volumes:
        - name: "certalliar"
          secret:
            secretName: "certalliar"
        - name: "grafana-data"
          persistentVolumeClaim:
            claimName: "grafana-pvc-data"
        - name: "grafana-ini"
          configMap:
            name: "conf-grafana"

